name: Build Rust Binary

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        # make_target: [release_linux, release_ios, release_windows]
        make_target: [release_linux]
    steps:
      - uses: actions/checkout@v2
      - name: set up rust
        uses: actions-rs/toolchain@v1

        with:
          toolchain: stable
      - name: install luajit
        run: sudo apt-get install -y libluajit-5.1-dev 
      - name: build binary
        run: make ${{ matrix.make_target }}
      - uses: endbug/add-and-commit@v9
        with:
          default_author: github_actions
          add: lua/
